phrase:
  project_id: a6b9c0fcc6018ece2aca977dd4fedf20
  push:
    sources:
      - file: ./app/en-us.json
        params:
          file_format: simple_json
          locale_id: 8e6ad4895a0ac1b62c0c14991fb35143
          autotranslate: false
          update_translations: true

  pull:
    targets:
      - file: ./app/i18n/locales/<locale_name>/translation.json
