phrase:
  project_id: 67c87c002493be13b0db9964ce093fed

  push:
    sources:
      - file: ./xlf.xlf
        params:
          file_format: xlf
          locale_id: en
          format_options:
            ignore_source_translations: true

  pull:
    targets:
      - file: ./xlf_trn.xlf
        params:
          file_format: xlf
          locale_id: en
          format_options:
            include_translation_state: true
