phrase:
  project_id: c0918e2795815f42683cb2503f4bd3ef

  push:
    sources:
      - file: ./xlf.xlf
        params:
          file_format: xlf
          locale_id: en
          format_options:
            ignore_source_translations: true

  pull:
    targets:
      - file: ./android.xml
        params:
          file_format: xml
          locale_id: en
          format_options:
            convert_placeholder: true
            indent_size: 20
