phrase:
  project_id: 67c87c002493be13b0db9964ce093fed

  push:
    sources:
      - file: ./source.json
        params:
          file_format: i18next_4
          locale_id: en

  pull:
    targets:
      - file: ./translations.json
        params:
          file_format: i18next_4
          locale_id: en
          format_options:
              nesting: false
