phrase:
  project_id: a6b9c0fcc6018ece2aca977dd4fedf20
  push:
    sources:
      - file: ./en_US.csv
        params:
          file_format: csv
          locale_id: 8e6ad4895a0ac1b62c0c14991fb35143
          locale_mapping:
            en-US: 1
          format_options:
            key_index: 1

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: csv
