phrase:
  access_token: f4c8c2dc59f46fc15e55c6028e90b2dd55a9ee86095a091ff339671446cf4259
  project_id: 67c87c002493be13b0db9964ce093fed

  push:
    sources:
      - file: ./en-translations.arb
        params:
          file_format: arb
          locale_id: en-US

  pull:
    targets:
      - file: ./translated.strings
        params:
          locale_id: zh
          file_format: strings
          encoding: UTF-16BE
