phrase:
  project_id: 67c87c002493be13b0db9964ce093fed

  push:
    sources:
      - file: ./en.json
        params:
          file_format: simple_json
          locale_id: en

  pull:
    targets:
      - file: ./nesting.json
        params:
          locale_id: en
          file_format: i18next_4  
          format_options:
            nesting: false
