phrase:
  project_id: a6b9c0fcc6018ece2aca977dd4fedf20
  push:
    sources:
      - file: ./en.json
        params:
          file_format: simple_json
          locale_id: 8e6ad4895a0ac1b62c0c14991fb35143
          tags: core

      - file: ./en_code.json
        params:
          file_format: json
          locale_id: 8e6ad4895a0ac1b62c0c14991fb35143
          tags: code

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: csv
