phrase:
  project_id: a6b9c0fcc6018ece2aca977dd4fedf20

  push:
    sources:
      - file: ./source.json
        params:
          file_format: simple_json
          locale_id: en

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
