phrase:
  project_id: 67c87c002493be13b0db9964ce093fed
  
  push:
    sources:
      - file: ./en.json
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true
          tags: uopdated-push
          tag_only_affected_keys: true

  pull:
    targets:
      - file: ./support/translations_<locale_code>.xlf
        params:
          file_format: xlf 
          format_options:
            include_translation_state: true
            indent_size: 20
