phrase:
  project_id: a6b9c0fcc6018ece2aca977dd4fedf20

  push:
    sources:
      - file: ./source.json
        params:
          file_format: simple_json
          locale_id: en

  pull:
    targets:
      - file: ./cs-CZ.json
        params:
          file_format: simple_json
          locale_id: d47d6ded473e0f2d363e384e4ca2c76b

      - file: ./en-GB.json
        params:
          file_format: simple_json
          locale_id: be05e810e5e60d2a4c36fc2865efda8b
