phrase:
  project_id: e81234013bf881d754b2535265954e36
  file_format: simple_json

  push:
    sources:
      - file: ./app/myself_en-US.json
        params:
          file_format: simple_json
          locale_id: en

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple_json
