phrase:
  access_token: 7e0f7771d53fc1781f2a3601e41e4c5c6bf124cf67a47c0ce7b8dcbd34851601
  project_id: e81234013bf881d754b2535265954e36

  push:
    sources:
      - file: ./app/
        params:
          file_format: simple.json
          locale_id: en

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: simple.json
