phrase:
  project_id: a6b9c0fcc6018ece2aca977dd4fedf20
  push:
    sources:
      - file: ./app/<locale_name>.json
        params:
          autotranslate: true
          update_translations: true

  pull:
    targets:
      - file: ./app/i18n/locales/<locale_name>/translation.json
