phrase:
  project_id: e81234013bf881d754b2535265954e36
  push:
    sources:
      - file: ./i18n/en_US.csv
        params:
          file_format: csv
          locale_id: 10b12abd2aece1b149d4051b133346f4
          locale_mapping:
            en-US: 1
          format_options:
            key_index: 1

  pull:
    targets:
      - file: ./<locale_name>.json
        params:
          file_format: csv
