phrase:
  project_id: 67c87c002493be13b0db9964ce093fed

  push:
    sources:
      - file: ./source.json
        params:
          file_format: i18next
          locale_id: en

  pull:
    targets:
      - file: ./translations.properties
        params:
          file_format: properties
          locale_id: en
          format_options:
            omit_separator_space: true
